apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keidai

resources:
  - namespace.yaml
  - serviceaccounts.yaml
  - pvc.yaml
  - configmap-fuda.yaml
  - configmap-apps.yaml
  - fuda.yaml
  - torii.yaml
  - shaiden.yaml
  - keidai-ui.yaml

configMapGenerator:
  - name: torii-config
    files:
      - torii.demo.yaml
    options:
      disableNameSuffixHash: true

# Secrets are created by deploy/k8s/up.sh from secrets.env (see secrets.example.env).
