apiVersion: v1
kind: ServiceAccount
metadata:
  name: fuda
  namespace: keidai
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: torii
  namespace: keidai
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shaiden
  namespace: keidai
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keidai-ui
  namespace: keidai
