apiVersion: v1
kind: ServiceAccount
metadata:
  name: fuda
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keidai.labels" . | nindent 4 }}
    app.kubernetes.io/name: fuda
{{- include "keidai.imagePullSecrets" . | nindent 0 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: torii
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keidai.labels" . | nindent 4 }}
    app.kubernetes.io/name: torii
{{- include "keidai.imagePullSecrets" . | nindent 0 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shaiden
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keidai.labels" . | nindent 4 }}
    app.kubernetes.io/name: shaiden
{{- include "keidai.imagePullSecrets" . | nindent 0 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keidai-ui
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keidai.labels" . | nindent 4 }}
    app.kubernetes.io/name: keidai-ui
{{- include "keidai.imagePullSecrets" . | nindent 0 }}
